import pkg from 'shelljs';
const { rm, exec, cp } = pkg;

rm('-rf', './dist/');
rm('-rf', './tsconfig.tsbuildinfo');
exec('yarn tsc');
rm('-rf', './tsconfig.tsbuildinfo');
cp('./package.json', './dist/package.json');
cp('./LICENSE', './dist/LICENSE');
rm('-rf', './dist/tsconfig.tsbuildinfo');
console.log('build over');
// rm('-rf', '..\\fast-start\\node_modules\\baja-lite\\baja-lite-field');
// cp('-R', './dist/*', '..\\fast-start\\node_modules\\baja-lite-field');
// console.log('fast-start over');
// rm('-rf', '..\\attack-service\\node_modules\\baja-lite\\baja-lite-field');
// cp('-R', './dist/*', '..\\attack-service\\node_modules\\baja-lite-field');
// console.log('attack-service over');
// rm('-rf', '..\\attack-front\\node_modules\\baja-lite\\baja-lite-field');
// cp('-R', './dist/*', '..\\attack-front\\node_modules\\baja-lite-field');
// console.log('attack-front over');
// cp('-R', './dist/*', '..\\entity\\node_modules\\baja-lite-field');
// console.log('entity over');
// cp('-R', './dist/*', '..\\wechat\\node_modules\\baja-lite-field');
// console.log('wechat over');
// cp('-R', './*', '..\\baja-lite\\baja-lite-field');
// console.log('cp over');